consta-design-system/charts

src/Bullet/__mocks__/mock.data.ts, src/Bullet/__stories__/Bullet.docs.mdx, src/Bullet/__stories__/examples/BulletExample/BulletExample.tsx, src/__private__/storybook/components/RemadeInfo/RemadeInfo.tsx
issue -  1388
Написала доку, добавила табличку со свойствами и примеры.
=> docs(Bullet): add docs and examples

src/Pie/__mocks__/mock.data.ts, src/Pie/__stories__/Pie.docs.mdx, src/Pie/__stories__/examples/PieExample/PieExample.tsx
Написала доку, добавила пример и табличку со свойствами
=> docs(Pie): edit docs, add props table & examples

src/Bar/__mocks__/mock.data.ts, src/Bar/__stories__/Bar.docs.mdx, src/Bar/__stories__/Bar.stories.tsx, src/Bar/__stories__/examples/BarExample/BarExample.tsx, src/Bar/types.ts
issue -  1402
Написала доку, добавила табличку и примеры, добавила необязательность к seriesField.
=> docs(Bar): add docs & examples

src/Line/__stories__/Line.docs.mdx, src/Line/__stories__/examples/LineExampleMeta/LineExampleMeta.tsx
issue -  1404
Добавила в доку описание, табличку свойств и пример
=> docs(Line): add docs and examples

src/Gauge/__stories__/Gauge.docs.mdx, src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx
[Issue (#1453)](https://github.com/gazprom-neft/consta-uikit/issues/1453)
* Добавлена страничка для документации с примером кода, визуальным исполнением и минималбным описанием
* Сделан пример, отображающий вариант стилизации компонента, как в фигме
=> Docs/gauge: стилизация

src/Radar/__mocks__/mock.data.ts, src/Radar/__stories__/Radar.docs.mdx, src/Radar/__stories__/examples/RadarExampleBasic/RadarExampleBasic.tsx, src/Radar/__stories__/examples/RadarExampleMulti/RadarExampleMulti.tsx
issue -  #1481
Написала доку, добавила примеров с данными по-русски. Оставила пример с английским — он клёвый.
=> docs(Radar): edit docs

src/Histogram/__stories__/Histogram.docs.mdx, src/Histogram/__stories__/Histogram.stories.tsx, src/Histogram/__stories__/examples/HistogramExampleAxis/HistogramExampleAxis.tsx, src/Histogram/__stories__/examples/HistogramExampleBasic/HistogramExampleBasic.tsx, src/Histogram/__stories__/examples/HistogramExampleBoxes/HistogramExampleBoxes.tsx, src/Histogram/__stories__/examples/HistogramExampleColor/HistogramExampleColor.tsx, src/Histogram/__stories__/examples/HistogramExampleStacked/HistogramExampleStacked.tsx
issue -  #1480
Дописала доку, добавила табличку и примеров.
=> docs(Histogram): edit docs, add examples

src/Gauge/__stories__/Gauge.docs.mdx, src/Gauge/__stories__/Gauge.stories.tsx, src/Gauge/__stories__/examples/GaugeExample/GaugeExample.tsx, src/Gauge/__stories__/examples/GaugeExampleIndicator/GaugeExampleIndicator.tsx, src/Gauge/__stories__/examples/GaugeExampleScale/GaugeExampleScale.tsx, src/Gauge/__stories__/examples/GaugeExampleStatistic/GaugeExampleStatistic.tsx
issue -  #1479
Дополнила доку, добавила примеров.
=> docs(Gauge): edit docs

package.json, yarn.lock
=> chore(deps): edit deps

src/Area/__stories__/Area.docs.mdx, src/Area/__stories__/Area.stories.tsx, src/Area/__stories__/examples/AreaExampleSlider/AreaExampleSlider.tsx, src/DualAxes/__stories__/DualAxes.docs.mdx, src/DualAxes/__stories__/DualAxes.stories.tsx, src/DualAxes/__stories__/examples/DualAxesExampleSlider/DualAxesExampleSlider.tsx, src/Line/__stories__/Line.docs.mdx, src/Line/__stories__/Line.stories.tsx, src/Line/__stories__/examples/LineExampleSlider/LineExampleSlider.tsx
issue -  [#1840](https://github.com/gazprom-neft/consta-uikit/issues/1840)
Добавлены примеры использования слайдера для масштабирования графиков
=> feat(Slider): add knobs, examples for lines scale

CHANGELOG.md, README.md, docs/start.stories.mdx
consta-design-system/uikit#1411
Поменяла ссылки на репозитории после переезда.
=> docs(common): edit links to github

package.json, yarn.lock
issue -  consta-design-system/uikit#1881
Обновлена версия  G2Plot и необходимых ему инструментов
=> chore(g2plot): update version of G2Plot and inner tools

src/__private__/components/Area/__stories__/Area.stories.tsx, src/__private__/components/DualAxes/__stories__/DualAxes.stories.tsx, src/__private__/hooks/useSlider/UseSlider.css, src/__private__/hooks/useSlider/__stories__/UseSlider.docs.mdx, src/__private__/hooks/useSlider/__stories__/UseSlider.stories.tsx, src/__private__/hooks/useSlider/index.tsx, src/__private__/hooks/useSlider/useSlider.tsx, src/useSlider/index.tsx
issue -  #consta-design-system/uikit#1959
Добавлен хук для стилизации слайдера
=> feat(useSlider): add hook for slider styling

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/pull_request_template.md, .storybook/manager.js, CHANGELOG.md, README.md, docs/start.stories.mdx
issue -  #2194
Поменяла ссылки на vercel
=> docs(common): change links to vercel

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/pull_request_template.md, CHANGELOG.md, README.md, docs/start.stories.mdx
=> docs(global): replace url

src/__private__/utils/legend.ts
issue -  consta-design-system/uikit#2272
=> fix(Legend): fix spacing on Legend

src/__private__/components/Area/__stories__/Area.stories.tsx, src/__private__/components/Bar/__stories__/Bar.stories.tsx, src/__private__/components/Bullet/__stories__/Bullet.stories.tsx, src/__private__/components/Column/__stories__/Column.stories.tsx, src/__private__/components/DualAxes/__stories__/DualAxes.stories.tsx, src/__private__/components/Histogram/__stories__/Histogram.stories.tsx, src/__private__/components/Line/__stories__/Line.stories.tsx, src/__private__/components/Pie/__stories__/Pie.stories.tsx, src/__private__/components/Scatter/__stories__/Scatter.stories.tsx
[issue -  #2452](https://github.com/consta-design-system/uikit/issues/2452)
Исправила ссылки на фигму там, где не работали.
=> docs(components): fix figma links

scripts/generateReExportsConfig.js, src/docs/create/create.stand.mdx, src/docs/create/create.stand.tsx, src/docs/start/start.stand.mdx, src/docs/start/start.stand.tsx, src/stand/standConfig.ts
=> docs(common): add common docs

package.json, src/components/Area/__stand__/Area.variants.tsx, src/components/Bar/__stand__/Bar.variants.tsx, src/components/Bullet/__stand__/Bullet.variants.tsx, src/components/Column/__mocks__/mock.data.ts, src/components/Column/__stand__/Column.variants.tsx, src/components/DualAxes/__stand__/DualAxes.variants.tsx, src/components/Gauge/__stand__/Gauge.variants.tsx, src/components/Histogram/__stand__/Histogram.variants.tsx, src/components/Line/__stand__/Line.stand.tsx, src/components/Line/__stand__/Line.variants.tsx, src/components/Pie/__stand__/Pie.variants.tsx, src/components/Radar/__stand__/Radar.variants.tsx, src/components/Scatter/__stand__/Scatter.variants.tsx, src/components/Waterfall/__stand__/Waterfall.variants.tsx, src/stand/standConfig.ts, yarn.lock
Добавила варианты для всех компонентов, кроме MixPlot.
=> docs: add new variants

src/components/Area/__stand__/Area.stand.tsx, src/components/Bar/__stand__/Bar.stand.tsx, src/components/Bullet/__stand__/Bullet.stand.tsx, src/components/Column/__stand__/Column.stand.tsx, src/components/DualAxes/__stand__/DualAxes.stand.tsx, src/components/Gauge/__stand__/Gauge.stand.tsx, src/components/Histogram/__stand__/Histogram.stand.tsx, src/components/Line/__stand__/Line.stand.tsx, src/components/MixPlot/__stand__/MixPlot.stand.tsx, src/components/Pie/__stand__/Pie.stand.tsx, src/components/Radar/__stand__/Radar.stand.tsx, src/components/Scatter/__stand__/Scatter.stand.tsx, src/components/Waterfall/__stand__/Waterfall.stand.tsx
Поменяла версии компонентов на версию, в которой они появились первый раз.
=> docs: change components version

README.md, package.json, src/stand/standConfig.ts, yarn.lock
- change links in readme
- add order to the stand
- change stand version
=> docs(portal): readme links, stand, version

src/components/Histogram/__stand__/Histogram.variants.tsx, src/components/Pie/__stand__/Pie.variants.tsx
closes consta-design-system/uikit#2482
=> fix(Variants): fix colors on dark theme

src/components/Bullet/Bullet.tsx
=> fix(Bullet): fixed label prop

src/utils/createNode.ts
closes consta-design-system/uikit#2760
=> fix(Charts): fix render for 18 react

src/components/BidirectionalBar/BidirectionalBar.tsx, src/components/BidirectionalBar/__mocks__/mock.data.ts, src/components/BidirectionalBar/__stand__/BidirectionalBar.dev.stand.mdx, src/components/BidirectionalBar/__stand__/BidirectionalBar.stand.mdx, src/components/BidirectionalBar/__stand__/BidirectionalBar.stand.tsx, src/components/BidirectionalBar/__stand__/BidirectionalBar.variants.tsx, src/components/BidirectionalBar/__stand__/examples/BidirectionalBarExample/BidirectionalBarExample.tsx, src/components/BidirectionalBar/__stand__/examples/BidirectionalBarLayoutExample/BidirectionalBarLayoutExample.tsx, src/components/BidirectionalBar/index.ts, src/components/BidirectionalBar/types.ts, src/stand/standConfig.ts, src/stand/standPageDecoration.tsx
closes consta-design-system/uikit#3107
=> feat(BidirectionalBar): add new chart

package.json, src/hooks/useSlider/useSlider.ts, yarn.lock
closes consta-design-system/uikit#2995
=> chore(Charts): update g2plot version

src/components/DualAxes/__stand__/DualAxes.variants.tsx
closes consta-design-system/uikit#2905
=> docs(DualAxed): fix variants

src/components/BidirectionalBar/__stand__/BidirectionalBar.image.svg
closes consta-design-system/uikit#3221
=> docs(BidirectionalBar): add image for stand

package.json, src/components/Pie/__stand__/Pie.dev.stand.mdx, src/components/Pie/__stand__/examples/PieExample/PieExample.tsx, src/stand/components/RemadeInfo/RemadeInfo.tsx, yarn.lock
=> chore: update uikit version
